repository: stackrocky/stackrocky.github.io
repository_url: https://github.com/stackrocky/stackrocky.github.io/

timezone: Asia/Shanghai
lang: zh_CN

title: StackRocky · Good.
alias_en: StackRocky
alias_cn: StackRocky
description: RockyStack
keywords: StackRocky.GitHub.Io
url: https://stackrocky.github.io
established_at: "2016-10-01T00:00+08:00"

author: Rocky
author_url: https://rocky-co.github.io
organization: Ha!
organization_url: https://rocky-co.github.io
contact: rocky[dot]dr[at]foxmail[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

home: https://StackRocky.github.io/

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
